# Generated by Django 5.0.2 on 2024-02-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_text_todo_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tittle',
            new_name='title',
        ),
    ]
